server:
  port: 8191
management:
  endpoints:
    web:
      exposure:
        include:
        - '*'
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver



